"""
Database Schemas for Coach Marketplace

Each Pydantic model maps to a MongoDB collection. Collection name is the
lowercase class name (e.g., Coach -> "coach").

These schemas are used for validation in API endpoints and for the autogenerated
schema viewer.
"""

from pydantic import BaseModel, Field, EmailStr, HttpUrl
from typing import Optional, List, Literal
from datetime import datetime

# ---------- Core Domain Schemas ----------

class ServiceOffering(BaseModel):
    name: str = Field(..., description="Service title, e.g., 1:1 Training")
    description: Optional[str] = Field(None, description="Short description of the service")
    rate_per_hour: float = Field(..., ge=0, description="Rate per hour in USD")

class AvailabilitySlot(BaseModel):
    weekday: Literal["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    start_time: str = Field(..., pattern=r"^[0-2]?[0-9]:[0-5][0-9]$", description="Start time 24h HH:MM")
    end_time: str = Field(..., pattern=r"^[0-2]?[0-9]:[0-5][0-9]$", description="End time 24h HH:MM")

class Coach(BaseModel):
    full_name: str = Field(..., description="Coach full name")
    email: EmailStr
    avatar_url: Optional[HttpUrl] = None
    bio: Optional[str] = Field(None, description="Short bio or experience summary")
    sports: List[str] = Field(default_factory=list, description="Sports coached, e.g. ['Tennis','Basketball']")
    location_city: Optional[str] = Field(None, description="City where the coach is based")
    location_state: Optional[str] = Field(None, description="State/Region")
    years_experience: Optional[int] = Field(None, ge=0, le=60)
    average_rating: Optional[float] = Field(0, ge=0, le=5)
    review_count: Optional[int] = Field(0, ge=0)
    services: List[ServiceOffering] = Field(default_factory=list)
    availability: List[AvailabilitySlot] = Field(default_factory=list)
    is_active: bool = True

class Athlete(BaseModel):
    full_name: str
    email: EmailStr
    user_type: Literal["adult", "parent"] = "adult"
    athlete_age: Optional[int] = Field(None, ge=1, le=120, description="Age of athlete if parent is booking")

class Review(BaseModel):
    coach_id: str
    athlete_name: str
    rating: int = Field(..., ge=1, le=5)
    comment: Optional[str] = None
    created_at: Optional[datetime] = None

class Booking(BaseModel):
    coach_id: str
    coach_name: Optional[str] = None
    athlete_name: str
    athlete_email: EmailStr
    user_type: Literal["adult", "parent"] = "adult"
    athlete_age: Optional[int] = Field(None, ge=1, le=120)
    service_name: str
    hourly_rate: float = Field(..., ge=0)
    duration_hours: float = Field(..., gt=0, le=8)
    scheduled_for: datetime
    status: Literal["pending", "confirmed", "completed", "cancelled"] = "pending"
